apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: gke-c1
  serverImage: datastax-docker.jfrog.io/datastax/dse-server:6.8.0-master-20190923204409-d9e0344
  serverVersion: 6.8.0
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gce-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  racks:
    - name: r1
    - name: r2
    - name: r3
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
