version:
  major: 0
  minor: 5
  patch: 0
  prerelease: "snapshot"
jenkins:
  master:
    plugins:
      - configuration-as-code
      - job-dsl
      - plain-credentials
      - github
      - blueocean
      - openstack-cloud
      - pipeline-githubnotify-step
      - timestamper
      - simple-theme-plugin
dev:
  dseImage: datastaxlabs/dse-k8s-server:6.8.0-20191113
  configBuilderImage: datastaxlabs/dse-k8s-config-builder:0.4.0-20191113
