apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dtcntr
spec:
  clusterName: clstr
  serverType: "dse"
  serverImage: datastax-docker.jfrog.io/datastax/dse-server:6.8.0-master-20190923204409-d9e0344
  serverVersion: 6.8.0
  size: 2
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "8000Mi"
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r0
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
