apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dsedatacenters.datastax.com
spec:
  group: datastax.com
  names:
    kind: DseDatacenter
    listKind: DseDatacenterList
    plural: dsedatacenters
    singular: dsedatacenter
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              additionalProperties:
                type: string
              description: Annotations
              type: object
            clusterName:
              description: DSE ClusterName
              type: string
            config:
              description: Definition file config
              type: string
            labels:
              additionalProperties:
                type: string
              description: Labels
              type: object
            parked:
              description: Parked state means we do not want any DSE processes running
              type: boolean
            racks:
              description: Racks is an exported field, BUT it is highly recommended
                that GetRacks() be used for accessing in order to handle the case
                where no rack is defined
              items:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: Annotations
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels
                    type: object
                  name:
                    description: The rack name
                    type: string
                required:
                - name
                type: object
              type: array
            repository:
              description: Repository to grab the DSE image from
              type: string
            resources:
              description: Resource requirements
              type: object
            size:
              description: The desired number of DSE server pods
              format: int32
              type: integer
            storageClaim:
              description: StorageClaim
              properties:
                resources:
                  description: Resource requirements
                  type: object
                storageclassname:
                  type: string
              required:
              - storageclassname
              type: object
            version:
              description: DSE Version
              type: string
          required:
          - size
          - version
          - clusterName
          - parked
          type: object
        status:
          properties:
            nodes:
              description: The number of the DSE server nodes
              format: int32
              type: integer
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
