apiVersion: datastax.com/v1alpha1
kind: DseDatacenter
metadata:
  name: dtcntr
spec:
  dseClusterName: clstr
  dseImage: datastax-docker.jfrog.io/datastax/dse-server:6.8.0-KO-14-dns-with-management-apis-20190809231145-b303270
  dseVersion: 6.8.0
  size: 2
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "8000Mi"
  storageClaim:
    storageclassname: standard
    resources:
      requests:
        storage: 1Gi
  racks:
    - name: r0
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
