apiVersion: datastax.com/v1alpha1
kind: DseDatacenter
metadata:
  name: dtcntr
spec:
  clusterName: clstr
  size: 2
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "8000Mi"
  storageClaim:
    storageclassname: standard
    resources:
      requests:
        storage: 1Gi
  racks:
    - name: r0
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
  repository: datastax-docker.jfrog.io/datastax/dse-server
  # we will want to update this once the management api branch has the
  # KO-14 changes
  version: 6.8.0-KO-14-dns-with-management-apis-20190809231145-b303270
