apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: example-cassandradatacenter
spec:
  clusterName: example-cluster
  serverImage: datastax-docker.jfrog.io/datastax/dse-server:6.8.0-master-20190923204409-d9e0344
  serverVersion: 6.8.0
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp2
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: rack0
    - name: rack1
    - name: rack2
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
