apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - us-west-2a
          - us-west-2b
          - us-east-1a
          - us-east-1b
          - eu-central-1a
          - eu-central-1b
          - ap-southeast-1a
          - ap-southeast-1b