# 1 rack, 2 nodes, DSE

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dtcntr
spec:
  clusterName: clstr
  serverImage: datastaxlabs/apache-cassandra-with-mgmtapi:3.11.6-20200316
  serverVersion: 6.8.0
  serverType: cassandra
  managementApiAuth:
    insecure: {}
  configBuilderImage: datastaxlabs/dse-k8s-config-builder:0.9.0-20200316
  size: 2
  superuserSecret: cassandra-superuser-secret
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: server-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r0
