# 1 rack, 2 nodes, has resource requests

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dtcntr
spec:
  clusterName: clstr
  serverType: "dse"
  serverImage: datastaxlabs/dse-k8s-server:6.8.0-20200316
  configBuilderImage: datastaxlabs/dse-k8s-config-builder:0.9.0-20200316
  serverVersion: 6.8.0
  size: 2
  managementApiAuth:
    insecure: {}
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "8000Mi"
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r0
  config:
    cassandra-yaml:
      authenticator: AllowAllAuthenticator
      batch_size_fail_threshold_in_kb: 1280
